// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: huaweiV8R10-ifm.proto

package huaweiV8R10_ifm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ifm_Interfaces_Interface_IfAdminStatus int32

const (
	Ifm_Interfaces_Interface_IfAdminStatus_DOWN Ifm_Interfaces_Interface_IfAdminStatus = 0
	Ifm_Interfaces_Interface_IfAdminStatus_UP   Ifm_Interfaces_Interface_IfAdminStatus = 1
)

// Enum value maps for Ifm_Interfaces_Interface_IfAdminStatus.
var (
	Ifm_Interfaces_Interface_IfAdminStatus_name = map[int32]string{
		0: "IfAdminStatus_DOWN",
		1: "IfAdminStatus_UP",
	}
	Ifm_Interfaces_Interface_IfAdminStatus_value = map[string]int32{
		"IfAdminStatus_DOWN": 0,
		"IfAdminStatus_UP":   1,
	}
)

func (x Ifm_Interfaces_Interface_IfAdminStatus) Enum() *Ifm_Interfaces_Interface_IfAdminStatus {
	p := new(Ifm_Interfaces_Interface_IfAdminStatus)
	*p = x
	return p
}

func (x Ifm_Interfaces_Interface_IfAdminStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ifm_Interfaces_Interface_IfAdminStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_huaweiV8R10_ifm_proto_enumTypes[0].Descriptor()
}

func (Ifm_Interfaces_Interface_IfAdminStatus) Type() protoreflect.EnumType {
	return &file_huaweiV8R10_ifm_proto_enumTypes[0]
}

func (x Ifm_Interfaces_Interface_IfAdminStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ifm_Interfaces_Interface_IfAdminStatus.Descriptor instead.
func (Ifm_Interfaces_Interface_IfAdminStatus) EnumDescriptor() ([]byte, []int) {
	return file_huaweiV8R10_ifm_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

type Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus int32

const (
	Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus_DOWN Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus = 0
	Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus_UP   Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus = 1
)

// Enum value maps for Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus.
var (
	Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus_name = map[int32]string{
		0: "IfOperStatus_DOWN",
		1: "IfOperStatus_UP",
	}
	Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus_value = map[string]int32{
		"IfOperStatus_DOWN": 0,
		"IfOperStatus_UP":   1,
	}
)

func (x Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus) Enum() *Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus {
	p := new(Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus)
	*p = x
	return p
}

func (x Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_huaweiV8R10_ifm_proto_enumTypes[1].Descriptor()
}

func (Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus) Type() protoreflect.EnumType {
	return &file_huaweiV8R10_ifm_proto_enumTypes[1]
}

func (x Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus.Descriptor instead.
func (Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus) EnumDescriptor() ([]byte, []int) {
	return file_huaweiV8R10_ifm_proto_rawDescGZIP(), []int{0, 0, 0, 1, 0}
}

type Ifm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interfaces *Ifm_Interfaces `protobuf:"bytes,5,opt,name=interfaces,proto3" json:"interfaces,omitempty"`
}

func (x *Ifm) Reset() {
	*x = Ifm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R10_ifm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ifm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ifm) ProtoMessage() {}

func (x *Ifm) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R10_ifm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ifm.ProtoReflect.Descriptor instead.
func (*Ifm) Descriptor() ([]byte, []int) {
	return file_huaweiV8R10_ifm_proto_rawDescGZIP(), []int{0}
}

func (x *Ifm) GetInterfaces() *Ifm_Interfaces {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type Ifm_Interfaces struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Interface []*Ifm_Interfaces_Interface `protobuf:"bytes,1,rep,name=interface,proto3" json:"interface,omitempty"`
}

func (x *Ifm_Interfaces) Reset() {
	*x = Ifm_Interfaces{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R10_ifm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ifm_Interfaces) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ifm_Interfaces) ProtoMessage() {}

func (x *Ifm_Interfaces) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R10_ifm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ifm_Interfaces.ProtoReflect.Descriptor instead.
func (*Ifm_Interfaces) Descriptor() ([]byte, []int) {
	return file_huaweiV8R10_ifm_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Ifm_Interfaces) GetInterface() []*Ifm_Interfaces_Interface {
	if x != nil {
		return x.Interface
	}
	return nil
}

type Ifm_Interfaces_Interface struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IfAdminStatus Ifm_Interfaces_Interface_IfAdminStatus  `protobuf:"varint,5,opt,name=ifAdminStatus,proto3,enum=huaweiV8R10_ifm.Ifm_Interfaces_Interface_IfAdminStatus" json:"ifAdminStatus,omitempty"`
	IfClearedStat *Ifm_Interfaces_Interface_IfClearedStat `protobuf:"bytes,9,opt,name=ifClearedStat,proto3" json:"ifClearedStat,omitempty"`
	IfDynamicInfo *Ifm_Interfaces_Interface_IfDynamicInfo `protobuf:"bytes,13,opt,name=ifDynamicInfo,proto3" json:"ifDynamicInfo,omitempty"`
	IfIndex       uint32                                  `protobuf:"varint,16,opt,name=ifIndex,proto3" json:"ifIndex,omitempty"`
	IfName        string                                  `protobuf:"bytes,25,opt,name=ifName,proto3" json:"ifName,omitempty"`
	IfStatistics  *Ifm_Interfaces_Interface_IfStatistics  `protobuf:"bytes,35,opt,name=ifStatistics,proto3" json:"ifStatistics,omitempty"`
}

func (x *Ifm_Interfaces_Interface) Reset() {
	*x = Ifm_Interfaces_Interface{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R10_ifm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ifm_Interfaces_Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ifm_Interfaces_Interface) ProtoMessage() {}

func (x *Ifm_Interfaces_Interface) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R10_ifm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ifm_Interfaces_Interface.ProtoReflect.Descriptor instead.
func (*Ifm_Interfaces_Interface) Descriptor() ([]byte, []int) {
	return file_huaweiV8R10_ifm_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Ifm_Interfaces_Interface) GetIfAdminStatus() Ifm_Interfaces_Interface_IfAdminStatus {
	if x != nil {
		return x.IfAdminStatus
	}
	return Ifm_Interfaces_Interface_IfAdminStatus_DOWN
}

func (x *Ifm_Interfaces_Interface) GetIfClearedStat() *Ifm_Interfaces_Interface_IfClearedStat {
	if x != nil {
		return x.IfClearedStat
	}
	return nil
}

func (x *Ifm_Interfaces_Interface) GetIfDynamicInfo() *Ifm_Interfaces_Interface_IfDynamicInfo {
	if x != nil {
		return x.IfDynamicInfo
	}
	return nil
}

func (x *Ifm_Interfaces_Interface) GetIfIndex() uint32 {
	if x != nil {
		return x.IfIndex
	}
	return 0
}

func (x *Ifm_Interfaces_Interface) GetIfName() string {
	if x != nil {
		return x.IfName
	}
	return ""
}

func (x *Ifm_Interfaces_Interface) GetIfStatistics() *Ifm_Interfaces_Interface_IfStatistics {
	if x != nil {
		return x.IfStatistics
	}
	return nil
}

type Ifm_Interfaces_Interface_IfClearedStat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SendByte   uint64 `protobuf:"varint,29,opt,name=sendByte,proto3" json:"sendByte,omitempty"`
	SendPacket uint64 `protobuf:"varint,36,opt,name=sendPacket,proto3" json:"sendPacket,omitempty"`
}

func (x *Ifm_Interfaces_Interface_IfClearedStat) Reset() {
	*x = Ifm_Interfaces_Interface_IfClearedStat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R10_ifm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ifm_Interfaces_Interface_IfClearedStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ifm_Interfaces_Interface_IfClearedStat) ProtoMessage() {}

func (x *Ifm_Interfaces_Interface_IfClearedStat) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R10_ifm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ifm_Interfaces_Interface_IfClearedStat.ProtoReflect.Descriptor instead.
func (*Ifm_Interfaces_Interface_IfClearedStat) Descriptor() ([]byte, []int) {
	return file_huaweiV8R10_ifm_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *Ifm_Interfaces_Interface_IfClearedStat) GetSendByte() uint64 {
	if x != nil {
		return x.SendByte
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfClearedStat) GetSendPacket() uint64 {
	if x != nil {
		return x.SendPacket
	}
	return 0
}

type Ifm_Interfaces_Interface_IfDynamicInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IfOperStatus Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus `protobuf:"varint,5,opt,name=ifOperStatus,proto3,enum=huaweiV8R10_ifm.Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus" json:"ifOperStatus,omitempty"`
}

func (x *Ifm_Interfaces_Interface_IfDynamicInfo) Reset() {
	*x = Ifm_Interfaces_Interface_IfDynamicInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R10_ifm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ifm_Interfaces_Interface_IfDynamicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ifm_Interfaces_Interface_IfDynamicInfo) ProtoMessage() {}

func (x *Ifm_Interfaces_Interface_IfDynamicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R10_ifm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ifm_Interfaces_Interface_IfDynamicInfo.ProtoReflect.Descriptor instead.
func (*Ifm_Interfaces_Interface_IfDynamicInfo) Descriptor() ([]byte, []int) {
	return file_huaweiV8R10_ifm_proto_rawDescGZIP(), []int{0, 0, 0, 1}
}

func (x *Ifm_Interfaces_Interface_IfDynamicInfo) GetIfOperStatus() Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus {
	if x != nil {
		return x.IfOperStatus
	}
	return Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus_DOWN
}

type Ifm_Interfaces_Interface_IfStatistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EthPortErrSts   *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts `protobuf:"bytes,1,opt,name=ethPortErrSts,proto3" json:"ethPortErrSts,omitempty"`
	RcvBroadPacket  uint64                                               `protobuf:"varint,2,opt,name=rcvBroadPacket,proto3" json:"rcvBroadPacket,omitempty"`
	RcvMutiPacket   uint64                                               `protobuf:"varint,5,opt,name=rcvMutiPacket,proto3" json:"rcvMutiPacket,omitempty"`
	RcvUniPacket    uint64                                               `protobuf:"varint,6,opt,name=rcvUniPacket,proto3" json:"rcvUniPacket,omitempty"`
	ReceiveByte     uint64                                               `protobuf:"varint,7,opt,name=receiveByte,proto3" json:"receiveByte,omitempty"`
	ReceivePacket   uint64                                               `protobuf:"varint,8,opt,name=receivePacket,proto3" json:"receivePacket,omitempty"`
	SendBroadPacket uint64                                               `protobuf:"varint,9,opt,name=sendBroadPacket,proto3" json:"sendBroadPacket,omitempty"`
	SendByte        uint64                                               `protobuf:"varint,10,opt,name=sendByte,proto3" json:"sendByte,omitempty"`
	SendMutiPacket  uint64                                               `protobuf:"varint,13,opt,name=sendMutiPacket,proto3" json:"sendMutiPacket,omitempty"`
	SendPacket      uint64                                               `protobuf:"varint,14,opt,name=sendPacket,proto3" json:"sendPacket,omitempty"`
	SendUniPacket   uint64                                               `protobuf:"varint,15,opt,name=sendUniPacket,proto3" json:"sendUniPacket,omitempty"`
}

func (x *Ifm_Interfaces_Interface_IfStatistics) Reset() {
	*x = Ifm_Interfaces_Interface_IfStatistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R10_ifm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ifm_Interfaces_Interface_IfStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ifm_Interfaces_Interface_IfStatistics) ProtoMessage() {}

func (x *Ifm_Interfaces_Interface_IfStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R10_ifm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ifm_Interfaces_Interface_IfStatistics.ProtoReflect.Descriptor instead.
func (*Ifm_Interfaces_Interface_IfStatistics) Descriptor() ([]byte, []int) {
	return file_huaweiV8R10_ifm_proto_rawDescGZIP(), []int{0, 0, 0, 2}
}

func (x *Ifm_Interfaces_Interface_IfStatistics) GetEthPortErrSts() *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts {
	if x != nil {
		return x.EthPortErrSts
	}
	return nil
}

func (x *Ifm_Interfaces_Interface_IfStatistics) GetRcvBroadPacket() uint64 {
	if x != nil {
		return x.RcvBroadPacket
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics) GetRcvMutiPacket() uint64 {
	if x != nil {
		return x.RcvMutiPacket
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics) GetRcvUniPacket() uint64 {
	if x != nil {
		return x.RcvUniPacket
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics) GetReceiveByte() uint64 {
	if x != nil {
		return x.ReceiveByte
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics) GetReceivePacket() uint64 {
	if x != nil {
		return x.ReceivePacket
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics) GetSendBroadPacket() uint64 {
	if x != nil {
		return x.SendBroadPacket
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics) GetSendByte() uint64 {
	if x != nil {
		return x.SendByte
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics) GetSendMutiPacket() uint64 {
	if x != nil {
		return x.SendMutiPacket
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics) GetSendPacket() uint64 {
	if x != nil {
		return x.SendPacket
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics) GetSendUniPacket() uint64 {
	if x != nil {
		return x.SendUniPacket
	}
	return 0
}

type Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RxAlignment   uint64 `protobuf:"varint,1,opt,name=rxAlignment,proto3" json:"rxAlignment,omitempty"`
	RxCRC         uint64 `protobuf:"varint,2,opt,name=rxCRC,proto3" json:"rxCRC,omitempty"`
	RxFragment    uint64 `protobuf:"varint,3,opt,name=rxFragment,proto3" json:"rxFragment,omitempty"`
	RxInrangeLen  uint64 `protobuf:"varint,4,opt,name=rxInrangeLen,proto3" json:"rxInrangeLen,omitempty"`
	RxJabber      uint64 `protobuf:"varint,5,opt,name=rxJabber,proto3" json:"rxJabber,omitempty"`
	RxJumboOctets uint64 `protobuf:"varint,6,opt,name=rxJumboOctets,proto3" json:"rxJumboOctets,omitempty"`
	RxLong        uint64 `protobuf:"varint,7,opt,name=rxLong,proto3" json:"rxLong,omitempty"`
	RxOverrun     uint64 `protobuf:"varint,8,opt,name=rxOverrun,proto3" json:"rxOverrun,omitempty"`
	RxPause       uint64 `protobuf:"varint,9,opt,name=rxPause,proto3" json:"rxPause,omitempty"`
	RxSymbol      uint64 `protobuf:"varint,10,opt,name=rxSymbol,proto3" json:"rxSymbol,omitempty"`
	RxUndersize   uint64 `protobuf:"varint,11,opt,name=rxUndersize,proto3" json:"rxUndersize,omitempty"`
	TxJumboOctets uint64 `protobuf:"varint,12,opt,name=txJumboOctets,proto3" json:"txJumboOctets,omitempty"`
	TxLost        uint64 `protobuf:"varint,13,opt,name=txLost,proto3" json:"txLost,omitempty"`
	TxOverrun     uint64 `protobuf:"varint,14,opt,name=txOverrun,proto3" json:"txOverrun,omitempty"`
	TxPause       uint64 `protobuf:"varint,15,opt,name=txPause,proto3" json:"txPause,omitempty"`
	TxSystem      uint64 `protobuf:"varint,16,opt,name=txSystem,proto3" json:"txSystem,omitempty"`
	TxUnderrun    uint64 `protobuf:"varint,17,opt,name=txUnderrun,proto3" json:"txUnderrun,omitempty"`
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) Reset() {
	*x = Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R10_ifm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) ProtoMessage() {}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R10_ifm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts.ProtoReflect.Descriptor instead.
func (*Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) Descriptor() ([]byte, []int) {
	return file_huaweiV8R10_ifm_proto_rawDescGZIP(), []int{0, 0, 0, 2, 0}
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetRxAlignment() uint64 {
	if x != nil {
		return x.RxAlignment
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetRxCRC() uint64 {
	if x != nil {
		return x.RxCRC
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetRxFragment() uint64 {
	if x != nil {
		return x.RxFragment
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetRxInrangeLen() uint64 {
	if x != nil {
		return x.RxInrangeLen
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetRxJabber() uint64 {
	if x != nil {
		return x.RxJabber
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetRxJumboOctets() uint64 {
	if x != nil {
		return x.RxJumboOctets
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetRxLong() uint64 {
	if x != nil {
		return x.RxLong
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetRxOverrun() uint64 {
	if x != nil {
		return x.RxOverrun
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetRxPause() uint64 {
	if x != nil {
		return x.RxPause
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetRxSymbol() uint64 {
	if x != nil {
		return x.RxSymbol
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetRxUndersize() uint64 {
	if x != nil {
		return x.RxUndersize
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetTxJumboOctets() uint64 {
	if x != nil {
		return x.TxJumboOctets
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetTxLost() uint64 {
	if x != nil {
		return x.TxLost
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetTxOverrun() uint64 {
	if x != nil {
		return x.TxOverrun
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetTxPause() uint64 {
	if x != nil {
		return x.TxPause
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetTxSystem() uint64 {
	if x != nil {
		return x.TxSystem
	}
	return 0
}

func (x *Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts) GetTxUnderrun() uint64 {
	if x != nil {
		return x.TxUnderrun
	}
	return 0
}

var File_huaweiV8R10_ifm_proto protoreflect.FileDescriptor

var file_huaweiV8R10_ifm_proto_rawDesc = []byte{
	0x0a, 0x15, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x30, 0x2d, 0x69, 0x66,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56,
	0x38, 0x52, 0x31, 0x30, 0x5f, 0x69, 0x66, 0x6d, 0x22, 0x96, 0x0f, 0x0a, 0x03, 0x49, 0x66, 0x6d,
	0x12, 0x3f, 0x0a, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52,
	0x31, 0x30, 0x5f, 0x69, 0x66, 0x6d, 0x2e, 0x49, 0x66, 0x6d, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x73, 0x52, 0x0a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x73, 0x1a, 0xcd, 0x0e, 0x0a, 0x0a, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73,
	0x12, 0x47, 0x0a, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31,
	0x30, 0x5f, 0x69, 0x66, 0x6d, 0x2e, 0x49, 0x66, 0x6d, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x09,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x1a, 0xf5, 0x0d, 0x0a, 0x09, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x0d, 0x69, 0x66, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x37,
	0x2e, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x30, 0x5f, 0x69, 0x66, 0x6d,
	0x2e, 0x49, 0x66, 0x6d, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x49, 0x66, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0d, 0x69, 0x66, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x5d, 0x0a, 0x0d, 0x69, 0x66, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e,
	0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x30, 0x5f, 0x69, 0x66, 0x6d, 0x2e,
	0x49, 0x66, 0x6d, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x49, 0x66, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x52, 0x0d, 0x69, 0x66, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x65,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x12, 0x5d, 0x0a, 0x0d, 0x69, 0x66, 0x44, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x68,
	0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x30, 0x5f, 0x69, 0x66, 0x6d, 0x2e, 0x49,
	0x66, 0x6d, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x49, 0x66, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x69, 0x66, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x66, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x10, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x66, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x16,
	0x0a, 0x06, 0x69, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x19, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x69, 0x66, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x5a, 0x0a, 0x0c, 0x69, 0x66, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x18, 0x23, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x68,
	0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x30, 0x5f, 0x69, 0x66, 0x6d, 0x2e, 0x49,
	0x66, 0x6d, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x49, 0x66, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x52, 0x0c, 0x69, 0x66, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x1a, 0x4b, 0x0a, 0x0d, 0x49, 0x66, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x65, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x18,
	0x1d, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x79, 0x74, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x24, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a,
	0xb5, 0x01, 0x0a, 0x0d, 0x49, 0x66, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x68, 0x0a, 0x0c, 0x69, 0x66, 0x4f, 0x70, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x44, 0x2e, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69,
	0x56, 0x38, 0x52, 0x31, 0x30, 0x5f, 0x69, 0x66, 0x6d, 0x2e, 0x49, 0x66, 0x6d, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x2e, 0x49, 0x66, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x49, 0x66, 0x4f, 0x70, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c, 0x69,
	0x66, 0x4f, 0x70, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3a, 0x0a, 0x0c, 0x49,
	0x66, 0x4f, 0x70, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x11, 0x49,
	0x66, 0x4f, 0x70, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x44, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x66, 0x4f, 0x70, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x5f, 0x55, 0x50, 0x10, 0x01, 0x1a, 0xf8, 0x07, 0x0a, 0x0c, 0x49, 0x66, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x6a, 0x0a, 0x0d, 0x65, 0x74, 0x68, 0x50,
	0x6f, 0x72, 0x74, 0x45, 0x72, 0x72, 0x53, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x44, 0x2e, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x30, 0x5f, 0x69, 0x66,
	0x6d, 0x2e, 0x49, 0x66, 0x6d, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x73,
	0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x49, 0x66, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x45, 0x74, 0x68, 0x50, 0x6f, 0x72, 0x74, 0x45,
	0x72, 0x72, 0x53, 0x74, 0x73, 0x52, 0x0d, 0x65, 0x74, 0x68, 0x50, 0x6f, 0x72, 0x74, 0x45, 0x72,
	0x72, 0x53, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x63, 0x76, 0x42, 0x72, 0x6f, 0x61, 0x64,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x72, 0x63,
	0x76, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x0d,
	0x72, 0x63, 0x76, 0x4d, 0x75, 0x74, 0x69, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0d, 0x72, 0x63, 0x76, 0x4d, 0x75, 0x74, 0x69, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x63, 0x76, 0x55, 0x6e, 0x69, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x72, 0x63, 0x76, 0x55, 0x6e, 0x69,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x42, 0x79, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x42, 0x79, 0x74, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x28,
	0x0a, 0x0f, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x73, 0x65, 0x6e, 0x64, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64,
	0x42, 0x79, 0x74, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64,
	0x42, 0x79, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x75, 0x74, 0x69,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x73, 0x65,
	0x6e, 0x64, 0x4d, 0x75, 0x74, 0x69, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x0d,
	0x73, 0x65, 0x6e, 0x64, 0x55, 0x6e, 0x69, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x55, 0x6e, 0x69, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x1a, 0x8d, 0x04, 0x0a, 0x0d, 0x45, 0x74, 0x68, 0x50, 0x6f, 0x72, 0x74, 0x45, 0x72,
	0x72, 0x53, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x78, 0x41, 0x6c, 0x69, 0x67, 0x6e, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x72, 0x78, 0x41, 0x6c, 0x69,
	0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x78, 0x43, 0x52, 0x43, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72, 0x78, 0x43, 0x52, 0x43, 0x12, 0x1e, 0x0a, 0x0a,
	0x72, 0x78, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x72, 0x78, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c,
	0x72, 0x78, 0x49, 0x6e, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0c, 0x72, 0x78, 0x49, 0x6e, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x4c, 0x65, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x78, 0x4a, 0x61, 0x62, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x72, 0x78, 0x4a, 0x61, 0x62, 0x62, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d,
	0x72, 0x78, 0x4a, 0x75, 0x6d, 0x62, 0x6f, 0x4f, 0x63, 0x74, 0x65, 0x74, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0d, 0x72, 0x78, 0x4a, 0x75, 0x6d, 0x62, 0x6f, 0x4f, 0x63, 0x74, 0x65,
	0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x78, 0x4c, 0x6f, 0x6e, 0x67, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x72, 0x78, 0x4c, 0x6f, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x78,
	0x4f, 0x76, 0x65, 0x72, 0x72, 0x75, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x72,
	0x78, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x75, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x78, 0x50, 0x61,
	0x75, 0x73, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x78, 0x50, 0x61, 0x75,
	0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x78, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x78, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x78, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0b, 0x72, 0x78, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x73, 0x69, 0x7a, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x74, 0x78, 0x4a, 0x75, 0x6d, 0x62, 0x6f, 0x4f, 0x63, 0x74, 0x65, 0x74,
	0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x74, 0x78, 0x4a, 0x75, 0x6d, 0x62, 0x6f,
	0x4f, 0x63, 0x74, 0x65, 0x74, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x4c, 0x6f, 0x73, 0x74,
	0x18, 0x0d, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x74, 0x78, 0x4c, 0x6f, 0x73, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x78, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x75, 0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x09, 0x74, 0x78, 0x4f, 0x76, 0x65, 0x72, 0x72, 0x75, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x78, 0x50, 0x61, 0x75, 0x73, 0x65, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74,
	0x78, 0x50, 0x61, 0x75, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x78, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x18, 0x10, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x78, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x78, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x72, 0x75, 0x6e,
	0x18, 0x11, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x74, 0x78, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x72,
	0x75, 0x6e, 0x22, 0x3d, 0x0a, 0x0d, 0x49, 0x66, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x49, 0x66, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x5f, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x49,
	0x66, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x55, 0x50, 0x10,
	0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_huaweiV8R10_ifm_proto_rawDescOnce sync.Once
	file_huaweiV8R10_ifm_proto_rawDescData = file_huaweiV8R10_ifm_proto_rawDesc
)

func file_huaweiV8R10_ifm_proto_rawDescGZIP() []byte {
	file_huaweiV8R10_ifm_proto_rawDescOnce.Do(func() {
		file_huaweiV8R10_ifm_proto_rawDescData = protoimpl.X.CompressGZIP(file_huaweiV8R10_ifm_proto_rawDescData)
	})
	return file_huaweiV8R10_ifm_proto_rawDescData
}

var file_huaweiV8R10_ifm_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_huaweiV8R10_ifm_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_huaweiV8R10_ifm_proto_goTypes = []interface{}{
	(Ifm_Interfaces_Interface_IfAdminStatus)(0),              // 0: huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfAdminStatus
	(Ifm_Interfaces_Interface_IfDynamicInfo_IfOperStatus)(0), // 1: huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfDynamicInfo.IfOperStatus
	(*Ifm)(nil),                                                 // 2: huaweiV8R10_ifm.Ifm
	(*Ifm_Interfaces)(nil),                                      // 3: huaweiV8R10_ifm.Ifm.Interfaces
	(*Ifm_Interfaces_Interface)(nil),                            // 4: huaweiV8R10_ifm.Ifm.Interfaces.Interface
	(*Ifm_Interfaces_Interface_IfClearedStat)(nil),              // 5: huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfClearedStat
	(*Ifm_Interfaces_Interface_IfDynamicInfo)(nil),              // 6: huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfDynamicInfo
	(*Ifm_Interfaces_Interface_IfStatistics)(nil),               // 7: huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfStatistics
	(*Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts)(nil), // 8: huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfStatistics.EthPortErrSts
}
var file_huaweiV8R10_ifm_proto_depIdxs = []int32{
	3, // 0: huaweiV8R10_ifm.Ifm.interfaces:type_name -> huaweiV8R10_ifm.Ifm.Interfaces
	4, // 1: huaweiV8R10_ifm.Ifm.Interfaces.interface:type_name -> huaweiV8R10_ifm.Ifm.Interfaces.Interface
	0, // 2: huaweiV8R10_ifm.Ifm.Interfaces.Interface.ifAdminStatus:type_name -> huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfAdminStatus
	5, // 3: huaweiV8R10_ifm.Ifm.Interfaces.Interface.ifClearedStat:type_name -> huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfClearedStat
	6, // 4: huaweiV8R10_ifm.Ifm.Interfaces.Interface.ifDynamicInfo:type_name -> huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfDynamicInfo
	7, // 5: huaweiV8R10_ifm.Ifm.Interfaces.Interface.ifStatistics:type_name -> huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfStatistics
	1, // 6: huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfDynamicInfo.ifOperStatus:type_name -> huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfDynamicInfo.IfOperStatus
	8, // 7: huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfStatistics.ethPortErrSts:type_name -> huaweiV8R10_ifm.Ifm.Interfaces.Interface.IfStatistics.EthPortErrSts
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_huaweiV8R10_ifm_proto_init() }
func file_huaweiV8R10_ifm_proto_init() {
	if File_huaweiV8R10_ifm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_huaweiV8R10_ifm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ifm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_huaweiV8R10_ifm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ifm_Interfaces); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_huaweiV8R10_ifm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ifm_Interfaces_Interface); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_huaweiV8R10_ifm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ifm_Interfaces_Interface_IfClearedStat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_huaweiV8R10_ifm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ifm_Interfaces_Interface_IfDynamicInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_huaweiV8R10_ifm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ifm_Interfaces_Interface_IfStatistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_huaweiV8R10_ifm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ifm_Interfaces_Interface_IfStatistics_EthPortErrSts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_huaweiV8R10_ifm_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_huaweiV8R10_ifm_proto_goTypes,
		DependencyIndexes: file_huaweiV8R10_ifm_proto_depIdxs,
		EnumInfos:         file_huaweiV8R10_ifm_proto_enumTypes,
		MessageInfos:      file_huaweiV8R10_ifm_proto_msgTypes,
	}.Build()
	File_huaweiV8R10_ifm_proto = out.File
	file_huaweiV8R10_ifm_proto_rawDesc = nil
	file_huaweiV8R10_ifm_proto_goTypes = nil
	file_huaweiV8R10_ifm_proto_depIdxs = nil
}
