// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: huaweiV8R10-trafficmng.proto

package huaweiV8R10_trafficmng

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trafficmng struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TmSlotSFUs *Trafficmng_TmSlotSFUs `protobuf:"bytes,4,opt,name=tmSlotSFUs,proto3" json:"tmSlotSFUs,omitempty"`
}

func (x *Trafficmng) Reset() {
	*x = Trafficmng{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R10_trafficmng_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trafficmng) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trafficmng) ProtoMessage() {}

func (x *Trafficmng) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R10_trafficmng_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trafficmng.ProtoReflect.Descriptor instead.
func (*Trafficmng) Descriptor() ([]byte, []int) {
	return file_huaweiV8R10_trafficmng_proto_rawDescGZIP(), []int{0}
}

func (x *Trafficmng) GetTmSlotSFUs() *Trafficmng_TmSlotSFUs {
	if x != nil {
		return x.TmSlotSFUs
	}
	return nil
}

type Trafficmng_TmSlotSFUs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TmSlotSFU []*Trafficmng_TmSlotSFUs_TmSlotSFU `protobuf:"bytes,1,rep,name=tmSlotSFU,proto3" json:"tmSlotSFU,omitempty"`
}

func (x *Trafficmng_TmSlotSFUs) Reset() {
	*x = Trafficmng_TmSlotSFUs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R10_trafficmng_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trafficmng_TmSlotSFUs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trafficmng_TmSlotSFUs) ProtoMessage() {}

func (x *Trafficmng_TmSlotSFUs) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R10_trafficmng_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trafficmng_TmSlotSFUs.ProtoReflect.Descriptor instead.
func (*Trafficmng_TmSlotSFUs) Descriptor() ([]byte, []int) {
	return file_huaweiV8R10_trafficmng_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Trafficmng_TmSlotSFUs) GetTmSlotSFU() []*Trafficmng_TmSlotSFUs_TmSlotSFU {
	if x != nil {
		return x.TmSlotSFU
	}
	return nil
}

type Trafficmng_TmSlotSFUs_TmSlotSFU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SfuStatisticss *Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss `protobuf:"bytes,1,opt,name=sfuStatisticss,proto3" json:"sfuStatisticss,omitempty"`
	SlotId         string                                          `protobuf:"bytes,2,opt,name=slotId,proto3" json:"slotId,omitempty"`
}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU) Reset() {
	*x = Trafficmng_TmSlotSFUs_TmSlotSFU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R10_trafficmng_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trafficmng_TmSlotSFUs_TmSlotSFU) ProtoMessage() {}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R10_trafficmng_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trafficmng_TmSlotSFUs_TmSlotSFU.ProtoReflect.Descriptor instead.
func (*Trafficmng_TmSlotSFUs_TmSlotSFU) Descriptor() ([]byte, []int) {
	return file_huaweiV8R10_trafficmng_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU) GetSfuStatisticss() *Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss {
	if x != nil {
		return x.SfuStatisticss
	}
	return nil
}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

type Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SfuStatistics []*Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics `protobuf:"bytes,1,rep,name=sfuStatistics,proto3" json:"sfuStatistics,omitempty"`
}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss) Reset() {
	*x = Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R10_trafficmng_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss) ProtoMessage() {}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R10_trafficmng_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss.ProtoReflect.Descriptor instead.
func (*Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss) Descriptor() ([]byte, []int) {
	return file_huaweiV8R10_trafficmng_proto_rawDescGZIP(), []int{0, 0, 0, 0}
}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss) GetSfuStatistics() []*Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics {
	if x != nil {
		return x.SfuStatistics
	}
	return nil
}

type Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChipId       uint32 `protobuf:"varint,1,opt,name=chipId,proto3" json:"chipId,omitempty"`
	DiscardCells uint64 `protobuf:"varint,2,opt,name=discardCells,proto3" json:"discardCells,omitempty"`
	PassCells    uint64 `protobuf:"varint,3,opt,name=passCells,proto3" json:"passCells,omitempty"`
	SendCells    uint64 `protobuf:"varint,4,opt,name=sendCells,proto3" json:"sendCells,omitempty"`
}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics) Reset() {
	*x = Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_huaweiV8R10_trafficmng_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics) ProtoMessage() {}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_huaweiV8R10_trafficmng_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics.ProtoReflect.Descriptor instead.
func (*Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics) Descriptor() ([]byte, []int) {
	return file_huaweiV8R10_trafficmng_proto_rawDescGZIP(), []int{0, 0, 0, 0, 0}
}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics) GetChipId() uint32 {
	if x != nil {
		return x.ChipId
	}
	return 0
}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics) GetDiscardCells() uint64 {
	if x != nil {
		return x.DiscardCells
	}
	return 0
}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics) GetPassCells() uint64 {
	if x != nil {
		return x.PassCells
	}
	return 0
}

func (x *Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics) GetSendCells() uint64 {
	if x != nil {
		return x.SendCells
	}
	return 0
}

var File_huaweiV8R10_trafficmng_proto protoreflect.FileDescriptor

var file_huaweiV8R10_trafficmng_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x30, 0x2d, 0x74, 0x72,
	0x61, 0x66, 0x66, 0x69, 0x63, 0x6d, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16,
	0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x30, 0x5f, 0x74, 0x72, 0x61, 0x66,
	0x66, 0x69, 0x63, 0x6d, 0x6e, 0x67, 0x22, 0xf0, 0x04, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x66, 0x66,
	0x69, 0x63, 0x6d, 0x6e, 0x67, 0x12, 0x4d, 0x0a, 0x0a, 0x74, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x53,
	0x46, 0x55, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x68, 0x75, 0x61, 0x77,
	0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x30, 0x5f, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x6d,
	0x6e, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x6d, 0x6e, 0x67, 0x2e, 0x54, 0x6d,
	0x53, 0x6c, 0x6f, 0x74, 0x53, 0x46, 0x55, 0x73, 0x52, 0x0a, 0x74, 0x6d, 0x53, 0x6c, 0x6f, 0x74,
	0x53, 0x46, 0x55, 0x73, 0x1a, 0x92, 0x04, 0x0a, 0x0a, 0x54, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x53,
	0x46, 0x55, 0x73, 0x12, 0x55, 0x0a, 0x09, 0x74, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x46, 0x55,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56,
	0x38, 0x52, 0x31, 0x30, 0x5f, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x6d, 0x6e, 0x67, 0x2e,
	0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x6d, 0x6e, 0x67, 0x2e, 0x54, 0x6d, 0x53, 0x6c, 0x6f,
	0x74, 0x53, 0x46, 0x55, 0x73, 0x2e, 0x54, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x46, 0x55, 0x52,
	0x09, 0x74, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x46, 0x55, 0x1a, 0xac, 0x03, 0x0a, 0x09, 0x54,
	0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x46, 0x55, 0x12, 0x6e, 0x0a, 0x0e, 0x73, 0x66, 0x75, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x46, 0x2e, 0x68, 0x75, 0x61, 0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x30, 0x5f, 0x74,
	0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x6d, 0x6e, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69,
	0x63, 0x6d, 0x6e, 0x67, 0x2e, 0x54, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x46, 0x55, 0x73, 0x2e,
	0x54, 0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x46, 0x55, 0x2e, 0x53, 0x66, 0x75, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x73, 0x52, 0x0e, 0x73, 0x66, 0x75, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x74,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64,
	0x1a, 0x96, 0x02, 0x0a, 0x0e, 0x53, 0x66, 0x75, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x73, 0x12, 0x7a, 0x0a, 0x0d, 0x73, 0x66, 0x75, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x54, 0x2e, 0x68, 0x75, 0x61,
	0x77, 0x65, 0x69, 0x56, 0x38, 0x52, 0x31, 0x30, 0x5f, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63,
	0x6d, 0x6e, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x6d, 0x6e, 0x67, 0x2e, 0x54,
	0x6d, 0x53, 0x6c, 0x6f, 0x74, 0x53, 0x46, 0x55, 0x73, 0x2e, 0x54, 0x6d, 0x53, 0x6c, 0x6f, 0x74,
	0x53, 0x46, 0x55, 0x2e, 0x53, 0x66, 0x75, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x73, 0x2e, 0x53, 0x66, 0x75, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x52, 0x0d, 0x73, 0x66, 0x75, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x1a,
	0x87, 0x01, 0x0a, 0x0d, 0x53, 0x66, 0x75, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x69, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x63, 0x68, 0x69, 0x70, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x64, 0x69, 0x73,
	0x63, 0x61, 0x72, 0x64, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0c, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x70, 0x61, 0x73, 0x73, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x70, 0x61, 0x73, 0x73, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x65, 0x6e, 0x64, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x73, 0x65, 0x6e, 0x64, 0x43, 0x65, 0x6c, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_huaweiV8R10_trafficmng_proto_rawDescOnce sync.Once
	file_huaweiV8R10_trafficmng_proto_rawDescData = file_huaweiV8R10_trafficmng_proto_rawDesc
)

func file_huaweiV8R10_trafficmng_proto_rawDescGZIP() []byte {
	file_huaweiV8R10_trafficmng_proto_rawDescOnce.Do(func() {
		file_huaweiV8R10_trafficmng_proto_rawDescData = protoimpl.X.CompressGZIP(file_huaweiV8R10_trafficmng_proto_rawDescData)
	})
	return file_huaweiV8R10_trafficmng_proto_rawDescData
}

var file_huaweiV8R10_trafficmng_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_huaweiV8R10_trafficmng_proto_goTypes = []interface{}{
	(*Trafficmng)(nil),                                                   // 0: huaweiV8R10_trafficmng.Trafficmng
	(*Trafficmng_TmSlotSFUs)(nil),                                        // 1: huaweiV8R10_trafficmng.Trafficmng.TmSlotSFUs
	(*Trafficmng_TmSlotSFUs_TmSlotSFU)(nil),                              // 2: huaweiV8R10_trafficmng.Trafficmng.TmSlotSFUs.TmSlotSFU
	(*Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss)(nil),               // 3: huaweiV8R10_trafficmng.Trafficmng.TmSlotSFUs.TmSlotSFU.SfuStatisticss
	(*Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics)(nil), // 4: huaweiV8R10_trafficmng.Trafficmng.TmSlotSFUs.TmSlotSFU.SfuStatisticss.SfuStatistics
}
var file_huaweiV8R10_trafficmng_proto_depIdxs = []int32{
	1, // 0: huaweiV8R10_trafficmng.Trafficmng.tmSlotSFUs:type_name -> huaweiV8R10_trafficmng.Trafficmng.TmSlotSFUs
	2, // 1: huaweiV8R10_trafficmng.Trafficmng.TmSlotSFUs.tmSlotSFU:type_name -> huaweiV8R10_trafficmng.Trafficmng.TmSlotSFUs.TmSlotSFU
	3, // 2: huaweiV8R10_trafficmng.Trafficmng.TmSlotSFUs.TmSlotSFU.sfuStatisticss:type_name -> huaweiV8R10_trafficmng.Trafficmng.TmSlotSFUs.TmSlotSFU.SfuStatisticss
	4, // 3: huaweiV8R10_trafficmng.Trafficmng.TmSlotSFUs.TmSlotSFU.SfuStatisticss.sfuStatistics:type_name -> huaweiV8R10_trafficmng.Trafficmng.TmSlotSFUs.TmSlotSFU.SfuStatisticss.SfuStatistics
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_huaweiV8R10_trafficmng_proto_init() }
func file_huaweiV8R10_trafficmng_proto_init() {
	if File_huaweiV8R10_trafficmng_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_huaweiV8R10_trafficmng_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trafficmng); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_huaweiV8R10_trafficmng_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trafficmng_TmSlotSFUs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_huaweiV8R10_trafficmng_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trafficmng_TmSlotSFUs_TmSlotSFU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_huaweiV8R10_trafficmng_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_huaweiV8R10_trafficmng_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Trafficmng_TmSlotSFUs_TmSlotSFU_SfuStatisticss_SfuStatistics); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_huaweiV8R10_trafficmng_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_huaweiV8R10_trafficmng_proto_goTypes,
		DependencyIndexes: file_huaweiV8R10_trafficmng_proto_depIdxs,
		MessageInfos:      file_huaweiV8R10_trafficmng_proto_msgTypes,
	}.Build()
	File_huaweiV8R10_trafficmng_proto = out.File
	file_huaweiV8R10_trafficmng_proto_rawDesc = nil
	file_huaweiV8R10_trafficmng_proto_goTypes = nil
	file_huaweiV8R10_trafficmng_proto_depIdxs = nil
}
